name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # manual

permissions:  # For Trusted Publishing
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: python -m build
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        attestations: true  # Включаем аттестации
        verbose: true
      # with:                                               # token version
      #   password: ${{ secrets.PYPI_API_TOKEN }}